name: CI/CD Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH va Deploy app len server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 24700
          script: |
            cd /var/www/STUDY-ONLINE
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker compose ps
            docker compose logs --tail=50
            curl -i https://dungnguyensec77.cloud
            curl -k https://dungnguyensec77.cloud






